To Do list: add & remove
Alondra87/ToDoList pull request #2
Opened 2022-06-03 20:28 UTC by Alondra87

**Description**
In this project, I build a simple HTML list of To Do tasks, using webpack to bundle JavaScript and applying ES6 syntax.
_Activity:_[ [https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md#project-requirements](https://github.com/Alondra87/Awesome-book-ES6/pull/url)](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

**Applied requirements**

- [ ] Remove all hardcoded items from the tasks array.
- [ ] Create a new JavaScript file for the new functionality.
- [ ] Implement a function for adding a new task.
- [ ] Implement a function for deleting a task.
- [ ] Implement a function for editing task descriptions.
- [ ] All changes to the To Do List should be saved in local storage.

2022-06-04 04:29 UTC, danielufeli requested changes
Hi @Alondra87, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Nice commits messages✔️
Descriptive PR ✔️
Good use of GitHub flow ✔️
Clean Code ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 04:29 UTC, danielufeli commented on src/modules/ToDoList.js
> +    this.index = index;
- [ ] Nice work here, as a requirement you need to set the index property to the value of the new array length (i.e. if a 5th task is added to the list, the index of that task should equal to 5). you can set `this.index = index + 1;`

2022-06-04 04:29 UTC, danielufeli commented on src/modules/ToDoList.js
> +  trashIcon.addEventListener('click', () => {
- [ ] Nice work here, there seems to be an issue when deleting a task, it deletes multiple tasks when you select 1 and the last task is not been deleted, also has a requirement Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique. find below a sample of how you can implement this.

```
trashIcon.addEventListener('click', () => {
    form.removeChild(list);
    const getFromLocalStorage = JSON.parse(localStorage.getItem('list'));
   let result;
    if(getFromLocalStorage) {
      result = getFromLocalStorage.filter((x, i) => x.task !== listText.textContent);
    }
    const reset = result.map((e, i) => {
      e.index = i + 1;
      return e;
    });
    localStorage.setItem('list', JSON.stringify(reset));
  });
```

2022-06-09 16:39 UTC, Alondra87 commented
Dear reviewer; I refactor all the code to avoid the bugs I was having, 

Description
In this project, I build a simple HTML list of To Do tasks, using webpack to bundle JavaScript and applying ES6 syntax.
Activity:[ [https://github.com/microverseinc/curriculum-javascript/blob/main/books/books_with_es6.md#project-requirements](https://github.com/Alondra87/Awesome-book-ES6/pull/url)](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

Applied requirements

- [x] -  Remove all hardcoded items from the tasks array.
- [x] -  Create a new JavaScript file for the new functionality.
- [x] -  Implement a function for adding a new task.
- [x] -  Implement a function for deleting a task.
- [x] -  Implement a function for editing task descriptions.
- [x] -  All changes to the To Do List should be saved in local storage.

2022-06-09 17:04 UTC, BenMukebo requested changes
Hi @Alondra87, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 

- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- You have a new JavaScript file for the new functionality.✔️
-  A function for adding a new task is implemented.✔️ 
-  A function for editing task descriptions is implemented.✔️ 
- Deleting a task updates all remaining items' indexes.✔️ 
- All changes to the To-Do List should be saved in local storage.✔️ 
 👍  Good job!



 ## Required Changes ♻️
_Check the comments under the review._

- [ ] `Linters` are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practices. Please Instead of disabling `eslint`, it will be nice to fix all linter errors manually.

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Please it will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser. You can put the steps to clone and run the project in a new Getting Started section under the project's description.


- [OPTIONAL ] Linters are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practices. Please Instead of disabling the client, it will be nice to fix all linter errors manually.

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 17:04 UTC, BenMukebo commented on src/style.css
> +} */
- [ ] Same here, Please do not leave unused code as a comment in your codebase. this will make your code much noisy, It is always a good practice to keep your code clean from such comments. 😉 💯

2022-06-09 17:04 UTC, BenMukebo commented on src/style.css
> +} */
- [ ] Please do not leave unused code as a comment in your codebase. this will make your code much noisy, It is always a good practice to keep your code clean from such comments. 😉 💯

2022-06-09 17:04 UTC, BenMukebo commented on src/index.js
> +// import loadTaskses from './modules/Tasks.js';
- [ ] Please do not leave unused code as a comment in your codebase. this will make your code much noisy, It is always a good practice to keep your code clean from such comments. 😉 💯

2022-06-09 17:04 UTC, BenMukebo commented on src/index.js
> +    // console.log(arrayTask);
- [ ] Do not commit console.log to your repo. It’s ugly, it kills performance and it can make confidential data be visible to anyone using the browser tools to look at your website. Please remove this 😜

2022-06-09 18:30 UTC, Alondra87 commented
Thanks @BenMukebo! A pplied all changes ♻️

2022-06-09 18:48 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @Alondra87 , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Excellent PR.
:heavy_check_mark: Well implemented required changes by previous reviewer.

### Optional suggestions :arrow_down_small: 

- [ ] The commit message should be written in the imperative tense and the first letter should be capitalized also. `Ex: "Fix bug" instead of "fixed bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-09 19:02 UTC, Alondra87 commented
Thanks for your comments @mahbubul14

2022-06-09 19:02 UTC, merged